drop table todos if exists;

create TABLE todos (
    id bigint generated by default as identity,
    todo VARCHAR(255),
    done boolean,
    primary key(id)
);


insert into todos (id, todo, done) values(1, 'hello', true);
insert into todos (id, todo, done) values(2, 'hi', true);
insert into todos (id, todo, done) values(3, 'smile', true);
